### ISSUE TITLE
larger than 2Gb

### ISSUE THREAD

**Issue by hoadudu** [markwylde/upload-to-bunny#3]
const fileContent = fs.readFileSync(sourcePath);
  readFileSync can only read files no larger than 2Gb, this packgage may not be able to upload large files.

**Comment by markwylde** [comment]
Nice catch. [Fixed](https://github.com/markwylde/upload-to-bunny/commit/5bee3de3271cfad4def319efbdc20e000d91e9a6) in v1.2.0.
